apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybridnet-manager
  namespace: kube-system
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      app: hybridnet-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hybridnet-manager
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: hybridnet-manager
              topologyKey: kubernetes.io/hostname
      priorityClassName: system-cluster-critical
      serviceAccountName: hybridnet
      hostNetwork: true
      containers:
        - name: hybridnet-manager
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /hybridnet/hybridnet-manager
            - --default-ip-retain={{ .Values.defualtIPRetain }}
            - --feature-gates=MultiCluster={{ .Values.multiCluster }},DualStack={{ .Values.dualStack }}
          env:
            - name: DEFAULT_NETWORK_TYPE
              value: {{ .Values.defualtNetworkType }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      nodeSelector:
        node-role.kubernetes.io/master: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybridnet-webhook
  namespace: kube-system
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      app: hybridnet-webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hybridnet-webhook
        webhook.hybridnet.io/ignore: "true"
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      serviceAccountName: hybridnet
      hostNetwork: true
      containers:
        - name: hybridnet-webhook
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /hybridnet/hybridnet-webhook
            - --default-ip-retain={{ .Values.defualtIPRetain }}
            - --feature-gates=MultiCluster={{ .Values.multiCluster }},DualStack={{ .Values.dualStack }}
          args:
            - --port=9898
          env:
            - name: DEFAULT_NETWORK_TYPE
              value: {{ .Values.defualtNetworkType }}
          ports:
            - containerPort: 9898
              name: webhook-port
