apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybridnet-manager
  namespace: kube-system
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      app: hybridnet-manager
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hybridnet-manager
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: hybridnet-manager
              topologyKey: kubernetes.io/hostname
      priorityClassName: system-cluster-critical
      serviceAccountName: hybridnet
      hostNetwork: true
      containers:
        - name: hybridnet-manager
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          imagePullPolicy: {{ .Values.images.hybridnet.imagePullPolicy }}
          {{- if .Values.manager.resources }}
          resources:
            {{- toYaml .Values.manager.resources | trim | nindent 12 }}
          {{- end }}
          ports:
            {{- if .Values.manager.metricsPort }}
            - name: http-metrics
              containerPort: {{ .Values.manager.metricsPort }}
              protocol: TCP
            {{- end }}
          command:
            - /hybridnet/hybridnet-manager
            - --default-ip-retain={{ .Values.defaultIPRetain }}
            - --feature-gates=MultiCluster={{ .Values.multiCluster }},VMIPRetain={{ .Values.vmIPRetain }}
            {{- if .Values.manager.controllerConcurrency }}
            - --controller-concurrency={{ .Values.manager.controllerConcurrency }}
            {{- end }}
            {{- if .Values.manager.kubeClientQPS }}
            - --kube-client-qps={{ .Values.manager.kubeClientQPS }}
            {{- end }}
            {{- if .Values.manager.kubeClientBurst }}
            - --kube-client-burst={{ .Values.manager.kubeClientBurst }}
            {{- end }}
            {{- if .Values.manager.metricsPort }}
            - --metrics-port={{ .Values.manager.metricsPort }}
            {{- end }}
          env:
            - name: DEFAULT_NETWORK_TYPE
              value: {{ .Values.defaultNetworkType }}
            - name: DEFAULT_IP_FAMILY
              value: {{ .Values.defaultIPFamily }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      nodeSelector:
        node-role.kubernetes.io/master: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybridnet-webhook
  namespace: kube-system
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      app: hybridnet-webhook
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hybridnet-webhook
        webhook.hybridnet.io/ignore: "true"
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      serviceAccountName: hybridnet
      hostNetwork: true
      containers:
        - name: hybridnet-webhook
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          imagePullPolicy: {{ .Values.images.hybridnet.imagePullPolicy }}
          {{- if .Values.webhook.resources }}
          resources:
            {{- toYaml .Values.webhook.resources | trim | nindent 12 }}
          {{- end }}
          command:
            - /hybridnet/hybridnet-webhook
            - --default-ip-retain={{ .Values.defaultIPRetain }}
            - --feature-gates=MultiCluster={{ .Values.multiCluster }},VMIPRetain={{ .Values.vmIPRetain }}
          args:
            - --port=9898
          env:
            - name: DEFAULT_NETWORK_TYPE
              value: {{ .Values.defaultNetworkType }}
            - name: DEFAULT_IP_FAMILY
              value: {{ .Values.defaultIPFamily }}
          ports:
            - containerPort: 9898
              name: webhook-port
