apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: hybridnet-validating-webhook
webhooks:
  - admissionReviewVersions: ["v1beta1", "v1"]
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNwRENDQVl3Q0NRQy9aTnM5bm9oY25UQU5CZ2txaGtpRzl3MEJBUXNGQURBVU1SSXdFQVlEVlFRRERBbG8KZVdKeWFXUnVaWFF3SGhjTk1qRXdPREkyTVRBeU16UTRXaGNOTXpFd09ESTBNVEF5TXpRNFdqQVVNUkl3RUFZRApWUVFEREFsb2VXSnlhV1J1WlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN3CmxlMFVWbXRiSkFYRmpodlFXdU8yNzBYRGNibU1sQmhrWTJldlZzWTNpNmVmRXdrYWllMmhCWGdLZFRncDVDSVcKOUFEa3JIY2p0aFFpL1AwTk5DRWpRK055TytKY0lVbUpQWE5XaWVRaG1hV0NzNlFzcWNOWk0zNUhsWTk2ekVVdgp1N3VQOGVOY1hmRXMyeWJ2RFFsRzVUT2pXTi8zNEFIQ1pRSmxpUkVtMUtUSm4zUko5SXNDbXlSYUhKNUF2ODVPClhralJqV0xkVm4wNlJNS3lUeDYxUjRQWTE0RTZYelRlWFk2T2pkT2ZtOWVtYXZTMUJLTGFOMDlBQWovdkoyejIKYzlTZkZMd0tJVkowR01TYXUwS2NNNlNCbUc2UGR5eE5PWmhBRExTOVZYUlMzN1NYeC9WRmQ5TFJMRk1wd3ljNQpZcVJENU1uK2tYNDh1VFU5N2RmTEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFSWmtBMENUZTRzCldUaU1WR0NOOEQwTjZtc2ZjYURRRjRUVDZNSEJUcjdOcklUMXZsMFlreHVGNXl4ajBDQ2E0bXBQRWNGNmJPcUcKdlQxcnZrZmdoakl2QnRFTVlUUEZ1dXNRZ2JmWU5zWVNkVjkzSVBYVkRTbkZITjdNRlBFMTZBd0xOQXBjUmpYKwpWV1FrNk1MU1RUcFQ2V3dWSUpHemsrZDhxakdYQlgyeE41YngwRDlpeU1oYzVjdnJkNDJHT1RFNko3UG0vTk5uCmdvZ2twYnRPaWRwMGJaVG1XQUkzbnUzNCtzRXQ2T2dzbFpweEt1OGlJanhnQlJrOHZDYXNBa0tMdDFFdXdOVUQKd1hBUGI5Wkl3clNEVFR5Nlg3cUZDSXdRMW9ZNVFFMW8xcUVrMTZROWk2VHNTUU5mbmIxQUxTNjJNcmp1dnZGUgplY21QMHpHSzd4WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: hybridnet-webhook
        namespace: kube-system
        port: 443
        path: "/validate"
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: hybridnet-v1.validating.hybridnet
    rules:
      - apiGroups: ["networking.alibaba.com"]
        apiVersions: ["v1"]
        operations: ["CREATE", "DELETE", "UPDATE"]
        resources: ["networks", "subnets"]
      - apiGroups: ["multicluster.alibaba.com"]
        apiVersions: ["v1"]
        operations: ["CREATE", "DELETE", "UPDATE"]
        resources: ["remoteclusters", "remotesubnets"]
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions: ["v1beta1", "v1"]
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNwRENDQVl3Q0NRQy9aTnM5bm9oY25UQU5CZ2txaGtpRzl3MEJBUXNGQURBVU1SSXdFQVlEVlFRRERBbG8KZVdKeWFXUnVaWFF3SGhjTk1qRXdPREkyTVRBeU16UTRXaGNOTXpFd09ESTBNVEF5TXpRNFdqQVVNUkl3RUFZRApWUVFEREFsb2VXSnlhV1J1WlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN3CmxlMFVWbXRiSkFYRmpodlFXdU8yNzBYRGNibU1sQmhrWTJldlZzWTNpNmVmRXdrYWllMmhCWGdLZFRncDVDSVcKOUFEa3JIY2p0aFFpL1AwTk5DRWpRK055TytKY0lVbUpQWE5XaWVRaG1hV0NzNlFzcWNOWk0zNUhsWTk2ekVVdgp1N3VQOGVOY1hmRXMyeWJ2RFFsRzVUT2pXTi8zNEFIQ1pRSmxpUkVtMUtUSm4zUko5SXNDbXlSYUhKNUF2ODVPClhralJqV0xkVm4wNlJNS3lUeDYxUjRQWTE0RTZYelRlWFk2T2pkT2ZtOWVtYXZTMUJLTGFOMDlBQWovdkoyejIKYzlTZkZMd0tJVkowR01TYXUwS2NNNlNCbUc2UGR5eE5PWmhBRExTOVZYUlMzN1NYeC9WRmQ5TFJMRk1wd3ljNQpZcVJENU1uK2tYNDh1VFU5N2RmTEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFSWmtBMENUZTRzCldUaU1WR0NOOEQwTjZtc2ZjYURRRjRUVDZNSEJUcjdOcklUMXZsMFlreHVGNXl4ajBDQ2E0bXBQRWNGNmJPcUcKdlQxcnZrZmdoakl2QnRFTVlUUEZ1dXNRZ2JmWU5zWVNkVjkzSVBYVkRTbkZITjdNRlBFMTZBd0xOQXBjUmpYKwpWV1FrNk1MU1RUcFQ2V3dWSUpHemsrZDhxakdYQlgyeE41YngwRDlpeU1oYzVjdnJkNDJHT1RFNko3UG0vTk5uCmdvZ2twYnRPaWRwMGJaVG1XQUkzbnUzNCtzRXQ2T2dzbFpweEt1OGlJanhnQlJrOHZDYXNBa0tMdDFFdXdOVUQKd1hBUGI5Wkl3clNEVFR5Nlg3cUZDSXdRMW9ZNVFFMW8xcUVrMTZROWk2VHNTUU5mbmIxQUxTNjJNcmp1dnZGUgplY21QMHpHSzd4WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: hybridnet-webhook
        namespace: kube-system
        port: 443
        path: "/validate"
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: core-v1.validating.hybridnet
    objectSelector:
      matchExpressions:
        - key: webhook.hybridnet.io/ignore
          operator: NotIn
          values: ["TRUE", "true"]
        {{ toYaml .Values.webhook.additionalPodMatchExpressions | nindent 8 }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 10

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hybridnet-mutating-webhook
webhooks:
  - admissionReviewVersions: ["v1beta1", "v1"]
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNwRENDQVl3Q0NRQy9aTnM5bm9oY25UQU5CZ2txaGtpRzl3MEJBUXNGQURBVU1SSXdFQVlEVlFRRERBbG8KZVdKeWFXUnVaWFF3SGhjTk1qRXdPREkyTVRBeU16UTRXaGNOTXpFd09ESTBNVEF5TXpRNFdqQVVNUkl3RUFZRApWUVFEREFsb2VXSnlhV1J1WlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN3CmxlMFVWbXRiSkFYRmpodlFXdU8yNzBYRGNibU1sQmhrWTJldlZzWTNpNmVmRXdrYWllMmhCWGdLZFRncDVDSVcKOUFEa3JIY2p0aFFpL1AwTk5DRWpRK055TytKY0lVbUpQWE5XaWVRaG1hV0NzNlFzcWNOWk0zNUhsWTk2ekVVdgp1N3VQOGVOY1hmRXMyeWJ2RFFsRzVUT2pXTi8zNEFIQ1pRSmxpUkVtMUtUSm4zUko5SXNDbXlSYUhKNUF2ODVPClhralJqV0xkVm4wNlJNS3lUeDYxUjRQWTE0RTZYelRlWFk2T2pkT2ZtOWVtYXZTMUJLTGFOMDlBQWovdkoyejIKYzlTZkZMd0tJVkowR01TYXUwS2NNNlNCbUc2UGR5eE5PWmhBRExTOVZYUlMzN1NYeC9WRmQ5TFJMRk1wd3ljNQpZcVJENU1uK2tYNDh1VFU5N2RmTEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFSWmtBMENUZTRzCldUaU1WR0NOOEQwTjZtc2ZjYURRRjRUVDZNSEJUcjdOcklUMXZsMFlreHVGNXl4ajBDQ2E0bXBQRWNGNmJPcUcKdlQxcnZrZmdoakl2QnRFTVlUUEZ1dXNRZ2JmWU5zWVNkVjkzSVBYVkRTbkZITjdNRlBFMTZBd0xOQXBjUmpYKwpWV1FrNk1MU1RUcFQ2V3dWSUpHemsrZDhxakdYQlgyeE41YngwRDlpeU1oYzVjdnJkNDJHT1RFNko3UG0vTk5uCmdvZ2twYnRPaWRwMGJaVG1XQUkzbnUzNCtzRXQ2T2dzbFpweEt1OGlJanhnQlJrOHZDYXNBa0tMdDFFdXdOVUQKd1hBUGI5Wkl3clNEVFR5Nlg3cUZDSXdRMW9ZNVFFMW8xcUVrMTZROWk2VHNTUU5mbmIxQUxTNjJNcmp1dnZGUgplY21QMHpHSzd4WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: hybridnet-webhook
        namespace: kube-system
        port: 443
        path: "/mutate"
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: core-v1.mutating.hybridnet
    objectSelector:
      matchExpressions:
        - key: webhook.hybridnet.io/ignore
          operator: NotIn
          values: ["TRUE", "true"]
        {{ toYaml .Values.webhook.additionalPodMatchExpressions | nindent 8 }}
    reinvocationPolicy: Never
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 10
