images:
  hybridnet:
    image: hybridnetdev/hybridnet
    tag: v0.8.5
    imagePullPolicy: IfNotPresent
  registryURL: "docker.io"

# -- It's always encouraged to use an overlay network to finish some general jobs in hybridnet. This
# chart will always create an "init" overlay Network/Subnet to initialize the K8s cluster. "init" Network/Subnet
# will only be created once.
init:
  # -- CIDR of "init" Subnet.
  cidr: 100.64.0.0/16

  # -- IP version of the init subnet. "4" for ipv4, "6" for ipv6
  ipVersion: "4"

  # -- VNI of the default overlay vxlan Network.
  vxlanID: 4

manager:
  # -- The number of manager pods, which is supposed to be less than or equal to the number of master nodes
  replicas: 3

  # -- Specifies the resources for the manager pods
  resources: {}
    # limits:
    #   cpu: 4000m
    #   memory: 4Gi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi

  # -- Specifies the concurrency configuration (a string of map) for manager pods
  controllerConcurrency: "Pod=1,IPAM=1,IPInstance=1"

  # -- Specifies the speed limits of manager pods to access apiserver
  kubeClientQPS: 300
  kubeClientBurst: 600

  # -- The port of manager to listen on for prometheus metrics
  metricsPort: 9899

  nodeSelector: {}


webhook:
  # -- Only the pods match the additionalPodMatchExpressions will be validate by hybridnet webhook.
  additionalPodMatchExpressions:
    - key: app
      operator: NotIn
      values: [ "kube-proxy" ]

  # -- The number of webhook pods, which is supposed to be less than or equal to the number of master nodes
  replicas: 3

  # -- Specifies the resources for the webhook pods
  resources: {}
    # limits:
    #   cpu: 4000m
    #   memory: 4Gi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi

  nodeSelector: {}

daemon:
  # -- Whether enable the felix components for NetworkPolicy.
  enableFelixPolicy: true

  # -- Whether clean felix policy iptables rules while policy is disabled.
  cleanFelixRulesWhilePolicyDisabled: true

  # -- The physical interfaces on each node to transmit vlan/vxlan/bgp packets, which should be confirmed
  # before network config is actually applied, or you might have to face the risk of rebooting the machine.
  #
  ## Each one of them is an interface name string list, using commons as separator. Daemon will always use
  ## the first available interface name in each list. If empty, daemon will choose interface by default route.
  preferVxlanInterfaces: ""
  preferVlanInterfaces: ""
  preferBGPInterfaces: ""

  # -- Hybridnet use policy routes to implement a L2 Vlan/Bridged network. To make the traffic closed to real
  # Vlan/Bridged traffic, hybridnet will append some addresses on the node forward interface for arp tricks.
  # This flag controls if daemon pods will append the "enhanced" addresses.
  enableVlanARPEnhancement: true

  # -- The CIDRs to select VTEP address on each node, using commons as separator.

  ## If it is empty, daemon on each node will take one of the valid address of the vxlan interface's parent
  ## (try ipv4 addresses first and then ipv6 addresses if no valid ipv4 address exists) as node's VTEP address
  ## randomly. If is is not empty, the first result matches any of the CIDRs will be chose as VTEP address.
  vtepAddressCIDRs: "0.0.0.0/0,::/0"

  # -- The community CNI plugins needed to be copied by hybridnet from inside container to the /opt/cni/bin/ directory of host
  neededCommunityCNIPlugins: "loopback,bandwidth"

  # -- The name of hybridnet CNI conf file generated in the /etc/cni/net.d/ directory of host
  cniConfName: "06-hybridnet.conflist"

  # -- Whether will daemon check the connectivity of local pod before staring it
  checkPodConnectivityFromHost: true

  # -- Specifies the resources for the cni-daemon containers
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 256Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  felix:
    # -- Specifies the resources for the felix container
    resources: {}
      # limits:
      #   cpu: 200m
      #   memory: 256Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

  livenessProbe:
    httpGet:
      path: /live
      port: 11021
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 5

typha:
  # -- The number of typha pods
  ## We recommend using Typha if you have more than 50 nodes.  Above 100 nodes it is essential.
  ## Use one replica for every 100-200 nodes.  In production, we recommend running at least 3
  ## replicas to reduce the impact of rolling upgrade.
  replicas: 3

  # -- The proxy server port of calico-typha on every node
  serverPort: 5473

  # -- Specifies the resources for the typha container
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 256Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

# -- Whether pod IP of stateful workloads will be retained by default. true or false
## Ref: https://github.com/alibaba/hybridnet/wiki/Static-pod-ip-addresses-for-StatefulSet
defaultIPRetain: true

# -- The default value when pod's network type is unspecified. Overlay or Underlay
## Ref: https://github.com/alibaba/hybridnet/wiki/Change-default-network-type
defaultNetworkType: Overlay

# -- Enable the MultiCluster feature. true or false
multiCluster: false

# -- The default value when pod's ip family is unspecified. IPv4 or IPv6 or DualStack
defaultIPFamily: IPv4

# -- Enable the support of retaining IP for kubevirt VM. true or false
vmIPRetain: false
